### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by Kelvincleon1234** [Lunarelly/LunarRanks#8]
how to make more permission than one?

**Comment by Lunarelly** [comment]
like that
```yaml
player:
    priority: 1
    color: "§7"
    display-name: "Player"
    chat-format: "§f{NAME}: §7{MESSAGE}" # Available tags: {NAME}, {DISPLAY_NAME}, {MESSAGE}
    name-tag: "§7{NAME}" # Available tags: {NAME}, {DISPLAY_NAME}, {PLATFORM}, {LINE}
    alias: "default"
    inheritance: []
    permissions:
      - permission.first
      - permission.second
```
